openapi: 3.0.0
info:
  version: v1
  title: UANATACA TSA API DOCUMENTATION
  description:
    $ref: ./tsa_gui.md
  x-logo:
    url: https://i.ibb.co/9vpW5vs/tsa-logo.png
    altText: Vol logo
servers:
  - url: 'https://tsa.uanataca.com'
    description: Main server

paths: {}