openapi: 3.0.0
info:
  version: v1
  title: UANATACA TSA API DOCUMENTATION
  description:
    $ref: ./tsa_gui.md
  x-logo:
    url: https://raw.githubusercontent.com/UANATACA/TSA-REPO/main/img/tsa_logo.png?token=ATF574S6N3GQ5SDJJGQ2Q6DALW6ZY
    altText: TSA logo
servers:
  - url: 'https://tsa.uanataca.com/tsa/tss03'
    description: Main server

paths: {}